### PR TITLE
Set statusline background to bg_alt, comment foreground change

### PR DESCRIPTION
**Pull request by booperlv**
Statusline background was previously a very light gray over the white text, and so I had changed it back to what I saw in the picture in the readme. I do not know whether or not this was intended.

Changed comment color to (subjectively) make it better, making it a slightly-lighter than background gray instead of the green that got confusing when it was near strings. This can probably be changed around and is again, subjective. Hope you can consider doing a similar change though :)

Before
current master

After
fork master

note: this lualine configuration uses the statusline highlight group for its background and foreground. Also, sorry for the bad example text: point is found in the top few lines though.

### CODE REVIEW

**Comment by shaunsingh** [comment]
Hi, thanks for the PR! I love the statusline improvements, I haven't tested it with lualine much so thank you for making it look much better. 

Is it fine if we swap the comment and string colors? As much as I like the grey, the green comment color is one of my favorite parts of the original theme.

**Comment by lynndylanhurley** [comment]
I also love the green comment colors.

**Comment by booperlv** [comment]
Just tried that out, Think it achieves the same things I had intended! I'll be pushing the changes in a few

**Comment by shaunsingh** [comment]
Looks great, thank you!

**Pull request merged**
